<?php include("layout.php"); ?>
<div class="container">
   <h1 style="padding-top:30px">Our API can convert these units.</h1>
   <h4>When using the API, make sure to enter the unit names as thay show here. For example, enter Cable_Lengths_International, not Cable Lengths International.</h4>
   <br>
   <hr>
   <p style = "font-size:15pt">
      Arpents
      <br>
      Cable_Lengths_International
      <br>
      Centimeters
      <br>
      Chains
      <br>
      Cubits
      <br>
      Decameters
      <br>
      Decimeters
      <br>
      Ells
      <br>
      Fathoms
      <br>
      Feet
      <br>
      Feet_French_measure
      <br>
      Fingers
      <br>
      Fingers_cloth
      <br>
      French
      <br>
      Furlongs
      <br>
      Gigameters
      <br>
      Hands
      <br>
      Inches
      <br>
      Kilofeet
      <br>
      Kilometers
      <br>
      Leagues
      <br>
      Leagues_land
      <br>
      Light_Days
      <br>
      Light_Hours
      <br>
      Light_Minutes
      <br>
      Light_Seconds
      <br>
      Light_Years
      <br>
      Line
      <br>
      Marathons
      <br>
      Megameters
      <br>
      Meters
      <br>
      Metric_Feet
      <br>
      Metric_Inches
      <br>
      Metric_Miles
      <br>
      Mickeys
      <br>
      Microinches
      <br>
      Micrometers
      <br>
      Microns
      <br>
      Mil
      <br>
      Miles
      <br>
      Millimeters
      <br>
      Myriameters
      <br>
      Nails_cloth
      <br>
      Nanometers
      <br>
      Nautical_Leagues
      <br>
      Nautical_Miles_International
      <br>
      Paces
      <br>
      Palms
      <br>
      Parsecs
      <br>
      Perch
      <br>
      Picas
      <br>
      Picometers
      <br>
      Points_PostScript
      <br>
      Quarters
      <br>
      Rods
      <br>
      Ropes
      <br>
      Shaku
      <br>
      Smoots
      <br>
      Spans
      <br>
      Steps
      <br>
      Terameters
      <br>
      Twips
      <br>
      Yards
      <br>
   </p>
</div>
<?php include("footer.php"); ?>